-- THE GYMIST SEED DATA

INSERT INTO workouts (slug, name, category, tier, short_description, image_url, image_alt, primary_muscles, secondary_muscles, equipment, steps, cues, mistakes, is_published, is_featured) VALUES
('barbell-back-squat', 'Barbell Back Squat', 'Strength', 2, 'A detailed guide for Barbell Back Squat', '/supabase-mock/barbell-back-squat.webp', 'Barbell Back Squat demonstrator', ARRAY['Quads','glutes'], ARRAY[]::text[], ARRAY['Barbell','rack'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('conventional-deadlift', 'Conventional Deadlift', 'Strength', 3, 'A detailed guide for Conventional Deadlift', '/supabase-mock/conventional-deadlift.webp', 'Conventional Deadlift demonstrator', ARRAY['Posterior chain'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('barbell-bench-press', 'Barbell Bench Press', 'Strength', 2, 'A detailed guide for Barbell Bench Press', '/supabase-mock/barbell-bench-press.webp', 'Barbell Bench Press demonstrator', ARRAY['Chest','triceps'], ARRAY[]::text[], ARRAY['Barbell','bench'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('overhead-press', 'Overhead Press', 'Strength', 2, 'A detailed guide for Overhead Press', '/supabase-mock/overhead-press.webp', 'Overhead Press demonstrator', ARRAY['Shoulders'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('romanian-deadlift', 'Romanian Deadlift', 'Strength', 2, 'A detailed guide for Romanian Deadlift', '/supabase-mock/romanian-deadlift.webp', 'Romanian Deadlift demonstrator', ARRAY['Hamstrings','glutes'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('front-rack-lunge', 'Front Rack Lunge', 'Strength', 2, 'A detailed guide for Front Rack Lunge', '/supabase-mock/front-rack-lunge.webp', 'Front Rack Lunge demonstrator', ARRAY['Quads','glutes'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('pull-up', 'Pull-Up', 'Strength', 2, 'A detailed guide for Pull-Up', '/supabase-mock/pull-up.webp', 'Pull-Up demonstrator', ARRAY['Lats','biceps'], ARRAY[]::text[], ARRAY['Bar'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('barbell-row', 'Barbell Row', 'Strength', 2, 'A detailed guide for Barbell Row', '/supabase-mock/barbell-row.webp', 'Barbell Row demonstrator', ARRAY['Mid back'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('dumbbell-bench-press', 'Dumbbell Bench Press', 'Hypertrophy', 1, 'A detailed guide for Dumbbell Bench Press', '/supabase-mock/dumbbell-bench-press.webp', 'Dumbbell Bench Press demonstrator', ARRAY['Chest'], ARRAY[]::text[], ARRAY['Dumbbells','bench'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'Hypertrophy', 1, 'A detailed guide for Dumbbell Shoulder Press', '/supabase-mock/dumbbell-shoulder-press.webp', 'Dumbbell Shoulder Press demonstrator', ARRAY['Shoulders'], ARRAY[]::text[], ARRAY['Dumbbells'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('lat-pulldown', 'Lat Pulldown', 'Hypertrophy', 1, 'A detailed guide for Lat Pulldown', '/supabase-mock/lat-pulldown.webp', 'Lat Pulldown demonstrator', ARRAY['Lats'], ARRAY[]::text[], ARRAY['Cable machine'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('seated-cable-row', 'Seated Cable Row', 'Hypertrophy', 1, 'A detailed guide for Seated Cable Row', '/supabase-mock/seated-cable-row.webp', 'Seated Cable Row demonstrator', ARRAY['Mid back'], ARRAY[]::text[], ARRAY['Cable machine'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('leg-press', 'Leg Press', 'Hypertrophy', 1, 'A detailed guide for Leg Press', '/supabase-mock/leg-press.webp', 'Leg Press demonstrator', ARRAY['Quads'], ARRAY[]::text[], ARRAY['Leg press machine'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('bulgarian-split-squat', 'Bulgarian Split Squat', 'Hypertrophy', 2, 'A detailed guide for Bulgarian Split Squat', '/supabase-mock/bulgarian-split-squat.webp', 'Bulgarian Split Squat demonstrator', ARRAY['Quads','glutes'], ARRAY[]::text[], ARRAY['Dumbbells','bench'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('hip-thrust', 'Hip Thrust', 'Hypertrophy', 2, 'A detailed guide for Hip Thrust', '/supabase-mock/hip-thrust.webp', 'Hip Thrust demonstrator', ARRAY['Glutes'], ARRAY[]::text[], ARRAY['Barbell','bench'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('kettlebell-swing', 'Kettlebell Swing', 'Conditioning', 2, 'A detailed guide for Kettlebell Swing', '/supabase-mock/kettlebell-swing.webp', 'Kettlebell Swing demonstrator', ARRAY['Posterior chain'], ARRAY[]::text[], ARRAY['Kettlebell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('farmers-carry', 'Farmer''s Carry', 'Conditioning', 1, 'A detailed guide for Farmer''s Carry', '/supabase-mock/farmers-carry.webp', 'Farmer''s Carry demonstrator', ARRAY['Grip','core'], ARRAY[]::text[], ARRAY['Dumbbells/handles'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('battle-ropes', 'Battle Ropes', 'Conditioning', 1, 'A detailed guide for Battle Ropes', '/supabase-mock/battle-ropes.webp', 'Battle Ropes demonstrator', ARRAY['Full body'], ARRAY[]::text[], ARRAY['Battle ropes'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('assault-bike-sprint', 'Assault Bike Sprint', 'Conditioning', 2, 'A detailed guide for Assault Bike Sprint', '/supabase-mock/assault-bike-sprint.webp', 'Assault Bike Sprint demonstrator', ARRAY['Full body'], ARRAY[]::text[], ARRAY['Air bike'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('box-jump', 'Box Jump', 'Conditioning', 2, 'A detailed guide for Box Jump', '/supabase-mock/box-jump.webp', 'Box Jump demonstrator', ARRAY['Legs','power'], ARRAY[]::text[], ARRAY['Plyo box'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('plank', 'Plank', 'Core', 1, 'A detailed guide for Plank', '/supabase-mock/plank.webp', 'Plank demonstrator', ARRAY['Core'], ARRAY[]::text[], ARRAY['Bodyweight'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 2, 'A detailed guide for Hanging Leg Raise', '/supabase-mock/hanging-leg-raise.webp', 'Hanging Leg Raise demonstrator', ARRAY['Lower abs'], ARRAY[]::text[], ARRAY['Bar'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('power-clean', 'Power Clean', 'Olympic', 3, 'A detailed guide for Power Clean', '/supabase-mock/power-clean.webp', 'Power Clean demonstrator', ARRAY['Full body'], ARRAY[]::text[], ARRAY['Barbell'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true),
('90-90-hip-mobility-flow', '90/90 Hip Mobility Flow', 'Mobility', 1, 'A detailed guide for 90/90 Hip Mobility Flow', '/supabase-mock/90-90-hip-mobility-flow.webp', '90/90 Hip Mobility Flow demonstrator', ARRAY['Hips'], ARRAY[]::text[], ARRAY['Mat'], '["Step 1: Setup","Step 2: Execution","Step 3: Return"]'::jsonb, '["Keep chest up","Brace core","Drive through heels"]'::jsonb, '[{"mistake":"Rounding back","fix":"Keep neutral spine"}]'::jsonb, true, true);

INSERT INTO instructors (slug, full_name, role, bio, portrait_url, specialities, categories, is_published) VALUES
('brian-otieno', 'Brian Otieno', 'Head Coach & Co-founder', 'Experienced coach specializing in Powerlifting, strength programming', '/supabase-mock/brian-otieno.webp', ARRAY['Powerlifting','strength programming'], ARRAY['Strength'], true),
('achieng-mboya', 'Achieng'' Mboya', 'Strength & Conditioning Coach', 'Experienced coach specializing in Women''s strength, postnatal return', '/supabase-mock/achieng-mboya.webp', ARRAY['Women''s strength','postnatal return'], ARRAY['Strength','Hypertrophy'], true),
('kevin-mwangi', 'Kevin Mwangi', 'Performance Coach', 'Experienced coach specializing in Hyrox, engine work, running', '/supabase-mock/kevin-mwangi.webp', ARRAY['Hyrox','engine work','running'], ARRAY['Conditioning'], true),
('njeri-kamau', 'Njeri Kamau', 'Mobility & Rehab Lead', 'Experienced coach specializing in Movement screening, injury-return', '/supabase-mock/njeri-kamau.webp', ARRAY['Movement screening','injury-return'], ARRAY['Mobility'], true),
('samuel-kiprotich', 'Samuel Kiprotich', 'Olympic Lifting Coach', 'Experienced coach specializing in Snatch, clean & jerk, athletic power', '/supabase-mock/samuel-kiprotich.webp', ARRAY['Snatch','clean & jerk','athletic power'], ARRAY['Olympic'], true),
('faith-wanjiru', 'Faith Wanjiru', 'Nutrition Coach & Trainer', 'Experienced coach specializing in Body composition, habit coaching', '/supabase-mock/faith-wanjiru.webp', ARRAY['Body composition','habit coaching'], ARRAY['Nutrition','Hypertrophy'], true),
('dennis-odhiambo', 'Dennis Odhiambo', 'Group Fitness Lead', 'Experienced coach specializing in Kettlebells, circuits, class energy', '/supabase-mock/dennis-odhiambo.webp', ARRAY['Kettlebells','circuits','class energy'], ARRAY['Conditioning'], true),
('aisha-hassan', 'Aisha Hassan', 'Youth & Beginner Coach', 'Experienced coach specializing in Ages 14–18, first-90-days onboarding', '/supabase-mock/aisha-hassan.webp', ARRAY['Ages 14–18','first-90-days onboarding'], ARRAY['Strength','Core'], true);

INSERT INTO blog_posts (slug, title, excerpt, body_md, cover_image_url, status, is_featured) VALUES
('how-much-protein-do-you-actually-need-a-kenyan-lifter-s-guide', 'How much protein do you actually need? A Kenyan lifter''s guide', 'Learn about How much protein do you actually need? A Kenyan lifter''s guide', '# How much protein do you actually need? A Kenyan lifter''s guide\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-1.webp', 'published', true),
('progressive-overload-the-only-training-principle-that-matters', 'Progressive overload: the only training principle that matters', 'Learn about Progressive overload: the only training principle that matters', '# Progressive overload: the only training principle that matters\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-2.webp', 'published', true),
('squat-depth-knees-over-toes-and-other-myths-that-won-t-die', 'Squat depth, knees over toes, and other myths that won''t die', 'Learn about Squat depth, knees over toes, and other myths that won''t die', '# Squat depth, knees over toes, and other myths that won''t die\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-3.webp', 'published', true),
('your-first-12-weeks-in-the-gym-a-week-by-week-plan', 'Your first 12 weeks in the gym: a week-by-week plan', 'Learn about Your first 12 weeks in the gym: a week-by-week plan', '# Your first 12 weeks in the gym: a week-by-week plan\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-4.webp', 'published', true),
('training-in-nairobi-s-altitude-and-dry-season-what-actually-changes', 'Training in Nairobi''s altitude and dry season — what actually changes', 'Learn about Training in Nairobi''s altitude and dry season — what actually changes', '# Training in Nairobi''s altitude and dry season — what actually changes\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-5.webp', 'published', true),
('sleep-is-a-performance-enhancing-drug-and-it-s-free', 'Sleep is a performance-enhancing drug (and it''s free)', 'Learn about Sleep is a performance-enhancing drug (and it''s free)', '# Sleep is a performance-enhancing drug (and it''s free)\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-6.webp', 'published', true),
('why-your-deadlift-stalls-at-100-kg-and-the-four-fixes', 'Why your deadlift stalls at 100 kg — and the four fixes', 'Learn about Why your deadlift stalls at 100 kg — and the four fixes', '# Why your deadlift stalls at 100 kg — and the four fixes\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-7.webp', 'published', true),
('eating-for-fat-loss-without-giving-up-kenyan-food', 'Eating for fat loss without giving up Kenyan food', 'Learn about Eating for fat loss without giving up Kenyan food', '# Eating for fat loss without giving up Kenyan food\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-8.webp', 'published', true),
('mobility-vs-stretching-what-your-hips-actually-need', 'Mobility vs stretching: what your hips actually need', 'Learn about Mobility vs stretching: what your hips actually need', '# Mobility vs stretching: what your hips actually need\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-9.webp', 'published', true),
('doms-soreness-and-the-recovery-myths-we-need-to-retire', 'DOMS, soreness and the recovery myths we need to retire', 'Learn about DOMS, soreness and the recovery myths we need to retire', '# DOMS, soreness and the recovery myths we need to retire\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-10.webp', 'published', true),
('strength-training-for-women-what-the-research-actually-says', 'Strength training for women: what the research actually says', 'Learn about Strength training for women: what the research actually says', '# Strength training for women: what the research actually says\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-11.webp', 'published', true),
('how-to-not-quit-in-week-three-the-psychology-of-habit-stacking', 'How to not quit in week three — the psychology of habit stacking', 'Learn about How to not quit in week three — the psychology of habit stacking', '# How to not quit in week three — the psychology of habit stacking\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\nDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n\n## Section 1\n\nSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.', '/supabase-mock/blog-12.webp', 'published', true);

